name: psych
favicon: null
layout_spectrum: 0.4452802313026041
typography_spectrum: 0.5587283067870885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5383412900846452
  lightness: 0.061306789284572005
  saturation: 0.1855168908368796
  rhythmicContrast: 0.9575013786088675
purpose: []
