name: psych
favicon: null
layout_spectrum: 0.99249
typography_spectrum: 0.49165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5383412900846452
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
